language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: s+k7cOKyX21F3nPP/7Tb3Tq050sS1l4WVtO1SIkXCU+wRy6WJZA0CtSCv5DIWKGZMIy3ZFJ7gYY2yMaJrUAUNOs/uWy4KlgTlWIylcK8Z6e5BKQwNqkqrjnkTzGdNN0PDSXgCqA0OgBJlZAu+0giO11Aq+xMxMInXjScqynu8Wa7szedrqN/nv3y1sdcKbvqinBIk1bTZf2Qvc653ml2AmRPeTxlS/hAdP4SSemj4ws/cisoG6NYLIF2OzFsL9LHxEGpA8A+IlYOMQUMm+3Tz2bg8zPMgole/fld4NA9eL+psOGxyY8Vq49c75LEHk8awz7Xf5XrdTR5+6qBV7TgdJttdcNn0bCOsK/eR+INvJkMonVRI8p8Q7Q0j9f0m5k4zOmSE5p8oKaCOr2vXtDnJPuHAaGSt8ce1Cf1gFFvGBrQ0aSjPGkhp0xMeyT11gFMABP2t4sJj824+Qk3+9Ue/QTd8NgyW9eK6VU/DSRoeUl5QtHcS26PXB7npnP+rwMm56zfzTNbuWJ2icrGpNRCIQ5SUoIdZa3zaphqIzZEiQhYBi+FlUQzglKdkoqYzEKWplRSDzO9eryk3O7RWGzgNvlrDsV7b0J431yzb9tzA1KC2M8LpMAjxFgVfvmxh7qkdX2E9TtOM/AGFaiua8Okq/cdBQb5mozpeSECQofsdew=
  app: boiling-river-55990
    on:
    repo: krothenbaum/node-restaurants-app-mongoose