language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: wVWIZm+Ra9g6EJaWVgvGIO1kVbapSq83MPzObdVNDvMtRZbohxN6cEY0wpNS+7yJMn+zJPpnilRrOeTnqa6fwRuBGpnGzswywweMsu/OzSnLkl8AOTcfZrmpCdjPirEGKtBmTgrnEs6nAr2kynlzd9RijH9zqCuvT97L8ncXto/P/hKKUfXoW52uz1iNlf2G0oh5v8CfayesbcxqFye3OG6VqwFRrXfOiJhYs9JsTdUZbmaz50jImEOy1Vb3VtInA83DwRXQkcc8rRd4T8mme9xivYr8KANb7yesips2s7Dcbx4kyTzTk3oj2BNYXd55MCEYQ8ICNjuLOHQVpwnJUubTaNAKNt4W7m1PcxMqZo2z4btEEhDjjATkFPW11IhCG7MGxTX0QyRJKohdlZGgY5seU/NaviqS4IdOWJA9H1odt5mAJxeCTdx61A68nWpBF1IP73SUvCTizFTzhdVFNNrJyyZTNUnzqQ5kAJ5Kl3NaNj0bDQAhle5wL63No6iRYj0LoyZ1NFVVfgoa9rynQbJ9AJEQdD/3aImLEJQ7lEr5/9L6NA2Q0tL6YPgNw08bX2Y5F6/9xFz+FNRI2JempcYrn/tDHiM+/RYsGjL73bRU6dNOgFw4QrEBuJsA0j+VrEPJ/RYGkdzhkaD9ZQHzrReIzYXwV78FKmjCWzw7qHM=
  app: boiling-river-55990
  on:
    repo: krothenbaum/node-restaurants-app-mongoose